```{r}
# Compile the Poisson NMF model fitting results into a single .RData
# file.
library(tools)
library(stringr)

# List all the RDS files containing the model fits.
files <- Sys.glob("../output/fit-*.rds")
n     <- length(files)

# Set up two data structures: "fits", a list used to store *all* the
# results; and "dat", a data frame summarizing the model parameters
# and optimization settings used to produce these fits.
fits   <- vector("list",n)
labels <- files
labels <- str_remove(labels,"../output/fit-")
labels <- str_remove(labels,".rds")
names(fits) <- labels
dat    <- data.frame(label       = labels,
                     k           = 3,
                     method      = "em",
                     extrapolate = FALSE,
                     stringsAsFactors = FALSE)

# Load all the results stored in the RDS files.
for (i in 1:n) {
  cat("*")
  fit                  <- readRDS(files[i])
  fits[[i]]            <- fit
  dat[i,"k"]           <- fit$k
  dat[i,"method"]      <- fit$method
  dat[i,"extrapolate"] <- fit$control$extrapolate
}
cat("\n")

# Reorder the results stored in "fits" and "dat".
dat  <- transform(dat,method = factor(method,c("em","ccd","scd")))
i    <- with(dat,order(k,extrapolate,method))
dat  <- dat[i,]
fits <- fits[i]
rownames(dat) <- NULL

# Convert the "k" column to a factor.
dat <- transform(dat,k = factor(k))

# Save the combined results to an .RData file.
cat("Saving combined results.\n")
save(list = c("dat","fits"),
     file = "fits.RData")
resaveRdaFiles("fits.RData")
```{r}
