---
title: "ConvertToDGE"
output: html_document
params:
  f: 'Harmony.Batchindividual.rds'
---
```{r}
library(Seurat)
library(Matrix)
library(dplyr)
library(scater)
library(scran)
library(edgeR)
```
This will convert a the SCTransformed counts (for genes expressed in > 20% of cells in at least 1 cluster) to pseudobulk expression values by cluster-batch-individual groups and store in a DGEList.

```{r}
path<- here::here("output/mergedObjects/")
merged<- readRDS(paste0(path,params$f))
```

```{r}
genelist<- read.table( "/project2/gilad/katie/Pilot_HumanEBs/Embryoid_Body_Pilot_Workflowr/output/GeneLists_by_minPCT/genelist.PCTthresh0.2_Harmony.Batchindividual.rds_SCT_snn_res.0.1.txt")
genelist<- as.vector(genelist$x)
```


```{r}
#subset merged to only the genes with PCT > min pct threshold in at least 1 cluster
submerged<- subset(merged, features = genelist )
```

```{r}
submerged<- as.SingleCellExperiment(submerged, assay="SCT")
```


```{r}
submerged<- convertTo(submerged, type= "edgeR")
```


```{r}
f<- gsub(".rds", "", params$f)
path<- here::here("output/DGELists/")
saveRDS(submerged, file=paste0(path,"dge_",f, "_minPCT0.2.rds")) 
```


