---
title: "Limma Res 0.8"
author: "Katie Rhodes"
date: "5/27/2021"
output: html_document
---
```{r, message=F}
library(Seurat)
library(Matrix)
library(dplyr)
library(edgeR)
library(limma)
```

choose parameters (integration type, clustering res, min pct threshold)
```{r}
f<- 'Harmony.Batchindividual'
pct<-0.2
res<- 'SCT_snn_res.0.8'
```

```{r}
path<- here::here("output/DGELists/")
dge<- readRDS(paste0(path,"Pseudobulk_dge_",f, "_", res,"_minPCT",pct,".rds"))
```

```{r}
genes.ribo <- grep('^RP',rownames(dge),value=T)
genes.no.ribo <- rownames(dge)[which(!(rownames(dge) %in% genes.ribo))]
dge$counts <- dge$counts[which(rownames(dge$counts) %in% genes.no.ribo),] #remove ribosomal genes
```

```{r}
dge<- calcNormFactors(dge, method="TMM")

summary(dge$samples$norm.factors)
```

```{r}
design<- model.matrix(~0+ dge$samples$cluster + dge$samples$batch + dge$samples$ind)
```


```{r}
v<- voom(dge, design, plot=TRUE)
v
```


```{r}
fit<- lmFit(v,design)
```

```{r}
nclust<- length(unique(dge$samples$cluster))
contrasts<- NULL
for (i in 1:nclust){
    c<- c(rep(-1,nclust),0,0,0,0)
    c[i]<- nclust-1
    
    contrasts<- cbind(contrasts, c)
}
```

```{r}
contrasts
```

```{r}
#first, testing all pairwise cluster comparisons. 
fit<- contrasts.fit(fit, contrasts= contrasts)
```

```{r}
efit<- eBayes(fit)
```

```{r}
plotSA(efit)
```

```{r}
summary(decideTests(efit))
```

```{r}
output.list<- list()
for (i in 1:nclust){
  ta<- topTable(efit, coef=i,n=nrow(fit))
  output.list[[i]]<- ta
}

listnames<- c(paste0("Cluster", unique(dge$samples$cluster)))
names(output.list)<- as.vector(listnames)

write.csv(output.list, "/project2/gilad/katie/Pilot_HumanEBs/Embryoid_Body_Pilot_Workflowr/output/Pseudobulk_Limma_res0.8_OnevAllTopTables.csv")
```

```{r}
sessionInfo()
```

