---
title: "Hierarchical Clustering-ComplexHeatmap"
output: html_document
---

```{r}
library(ComplexHeatmap)
library(edgeR)
```


```{r}
f<- 'Harmony.Batchindividual'
pct<-0.2
res<- 'SCT_snn_res.0.1'
```

```{r}
path<- here::here("output/DGELists/")
dge<- readRDS(paste0(path,"Pseudobulk_dge_",f, "_", res,"_minPCT",pct,".rds"))
```

```{r}
pseudo.lcpm<- cpm(dge, log=TRUE)
```

```{r}
#clean names
replicate<- as.character(dge$samples$batch)
replicate[replicate == "Batch1"]<- "1"
replicate[replicate == "Batch2"]<- "2"
replicate[replicate == "Batch3"]<- "3"

dge$samples<- cbind(dge$samples, replicate)

dge$samples$ind<- as.character(dge$samples$ind)
dge$samples$ind[dge$samples$ind == "NA18511"]<- "18511"
dge$samples$ind[dge$samples$ind == "NA19160"]<- "19160"
dge$samples$ind[dge$samples$ind == "NA18858"]<- "18858"
```


```{r}
ha<- HeatmapAnnotation(cluster= dge$samples$cluster, replicate= dge$samples$replicate, individual= dge$samples$ind)

p<- Heatmap(pseudo.lcpm, bottom_annotation = ha, show_column_names = F, show_row_names = F, name = "lcpm", use_raster = TRUE)

p
```


```{r, eval=F}
png(file= "/project2/gilad/katie/Pilot_HumanEBs/Embryoid_Body_Pilot_Workflowr/output/figs/Fig4_HierClustwRibo.png", width=8, height=4.5, units= "in", res=1080)

p
  
dev.off()
```

Same thing, removing ribosomal to see if it changes anything

```{r}
genes.ribo <- grep('^RP',rownames(dge),value=T)
genes.no.ribo <- rownames(dge)[which(!(rownames(dge) %in% genes.ribo))]
dge$counts <- dge$counts[which(rownames(dge$counts) %in% genes.no.ribo),] #remove ribosomal genes
```

```{r}
pseudo.lcpm<- cpm(dge, log=TRUE)
```

```{r}
ha<- HeatmapAnnotation(cluster= dge$samples$cluster, replicate= dge$samples$replicate, individual= dge$samples$ind, 
                       col = list(cluster= c("0"='#EE6677', "1"='#228833', "2"='#4477AA', "3"='#CCBB44', "4"= '#66CCEE', "5"='#AA3377', "6"= '#BBBBBB'),
                       replicate= c("1"= "#56B4E9", "2"="#009E73", "3"="#0072B2"),
                       individual= c("18511"="#F0E442", "19160"="#D55E00", "18858"="#CC79A7")))




V<- Heatmap(pseudo.lcpm, bottom_annotation = ha, show_column_names = F, show_row_names = F, name = "lcpm", use_raster = TRUE)

V
```

```{r, eval=F}
png(file= "/project2/gilad/katie/Pilot_HumanEBs/Embryoid_Body_Pilot_Workflowr/output/figs/Fig4_HierClustNoRibo.png", width=8, height=4.5, units= "in", res=1080)

V
  
dev.off()
```

```{r}
sessionInfo()
```

